// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANUlYojLtINpg01RYFJ8uiBHBkno8On4A',
    appId: '1:751642516656:web:9a1d549e71bb8c4a80af75',
    messagingSenderId: '751642516656',
    projectId: 'chat-appp-4f423',
    authDomain: 'chat-appp-4f423.firebaseapp.com',
    storageBucket: 'chat-appp-4f423.firebasestorage.app',
    measurementId: 'G-GF91JRV03D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrlp0Rm_558l672XUuSDL0Rn4fioNzkb0',
    appId: '1:751642516656:android:0c467732fca989ce80af75',
    messagingSenderId: '751642516656',
    projectId: 'chat-appp-4f423',
    storageBucket: 'chat-appp-4f423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5RPgJcYRhgkpIokbvrrrfc1qmUgS5BtM',
    appId: '1:751642516656:ios:9c4df9c143a3eb1c80af75',
    messagingSenderId: '751642516656',
    projectId: 'chat-appp-4f423',
    storageBucket: 'chat-appp-4f423.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5RPgJcYRhgkpIokbvrrrfc1qmUgS5BtM',
    appId: '1:751642516656:ios:9c4df9c143a3eb1c80af75',
    messagingSenderId: '751642516656',
    projectId: 'chat-appp-4f423',
    storageBucket: 'chat-appp-4f423.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANUlYojLtINpg01RYFJ8uiBHBkno8On4A',
    appId: '1:751642516656:web:a659edbb5075916480af75',
    messagingSenderId: '751642516656',
    projectId: 'chat-appp-4f423',
    authDomain: 'chat-appp-4f423.firebaseapp.com',
    storageBucket: 'chat-appp-4f423.firebasestorage.app',
    measurementId: 'G-PBTF5ZDM97',
  );
}
